In [1]:
import numpy as np

In [5]:
a = np.ones(shape = (1, 3)) * 2
b = np.ones(shape = (3, 1)) * 5
c = np.ones(shape = (1, 3)) * 4


In [14]:
s = a * b
s

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [10]:
x = np.array([1,2,3,4])

In [11]:
x

array([1, 2, 3, 4])

In [9]:
x.shape

(3,)

In [12]:
x[:, None]

array([[1],
       [2],
       [3],
       [4]])

In [15]:
s * x

ValueError: operands could not be broadcast together with shapes (3,3) (4,) 

In [18]:
def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))

In [32]:
import numpy as np


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


x = np.array([0.5, 0.1, -0.2])
target = 0.6
learnrate = 0.5

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)

## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)

# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)


Change in weights for hidden layer to output layer:
[0.00804047 0.00555918]
Change in weights for input layer to hidden layer:
[[ 1.77005547e-04 -5.11178506e-04]
 [ 3.54011093e-05 -1.02235701e-04]
 [-7.08022187e-05  2.04471402e-04]]


In [26]:
output = sigmoid(output_layer_in)

In [27]:
weights_hidden_output.shape

(2,)

In [28]:
hidden_layer_output.shape

(2,)

In [29]:
output_layer_in.shape

()

In [30]:
output_layer_in

-0.06012438223148006

In [35]:
hidden_error_term

array([ 0.00070802, -0.00204471])

In [36]:
x[:, None]

array([[ 0.5],
       [ 0.1],
       [-0.2]])

In [37]:
hidden_error_term * x[:, None]

array([[ 3.54011093e-04, -1.02235701e-03],
       [ 7.08022187e-05, -2.04471402e-04],
       [-1.41604437e-04,  4.08942805e-04]])